Repository boostcamp-2020/Project04-C-Whale, pull requests merged in 2020-12, with the labels that each got.

#127 concurrent 적용 & 프로젝트 UI 샘플 구현
  client/.eslintrc.js
  client/package-lock.json
  client/src/api/myAxios.js
  client/src/components/project/index.vue
  client/src/views/Login.vue
  client/src/views/Project.vue
  client/vue.config.js
  server/package-lock.json
  server/package.json
  server/src/controllers/user.js
Labels: FE

#129 프로젝트, 작업 API 수정 / 프로젝트 화면 기능 추가 (수정기능)
  client/.env.sample
  client/src/api/task.js
  client/src/components/project/AddTask.vue
  client/src/components/project/index.vue
  client/src/store/project.js
  client/src/views/Home.vue
  client/src/views/Login.vue
  server/src/controllers/project.js
  server/src/controllers/task.js
  server/src/models/section.js
  server/src/models/seeders/index.js
  server/src/routes/task.js
  server/src/utils/date.js
Labels: API, BE, FE

#126 작업 완료 로직 구현 및 보기 모드 구현
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO/Sources/Models/Priority+PopoverViewModelType.swift
  iOS/HalgoraeDO/Sources/Models/Priority.swift
  iOS/HalgoraeDO/Sources/Models/Task.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskAddViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskBoardViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskList.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListDisplayLogic.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListInteractor.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListModels.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListPresenter.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListWorker.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskCollectionViewListCell.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskContentConfigure.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskContentView.swift
  iOS/HalgoraeDO/Sources/Views/RoundButton.swift
Labels: :whale: iOS

#128 보드로 보기 구조 변경
  .DS_Store
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO/Sources/Models/Task.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskAddViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskBoardViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/AddSectionViewCell.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskSectionViewCell.swift
Labels: :whale: iOS

#131 #102 작업 및 섹션 추가 기능 구현
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskAddViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskBoardViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/AddSectionViewCell.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskBoardSupplementaryView.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskSectionViewCell.swift
Labels: :whale: iOS

#133 작업 완료 처리 구현 완료
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListInteractor.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListPresenter.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskCollectionViewListCell.swift
  iOS/HalgoraeDO/Sources/Views/Base.lproj/Main.storyboard
  iOS/HalgoraeDO/Sources/Views/ConfirmActionView/ConfirmActionView.swift
  iOS/HalgoraeDO/Sources/Views/ConfirmActionView/ConfirmActionView.xib
Labels: :whale: iOS

#136 Custom Color assets 추가
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO/Resources/Colors.xcassets/Contents.json
  iOS/HalgoraeDO/Resources/Colors.xcassets/halgoraedoDarkBlue.colorset/Contents.json
  iOS/HalgoraeDO/Resources/Colors.xcassets/halgoraedoMint.colorset/Contents.json
  iOS/HalgoraeDO/Sources/Utils/UIColor+.swift
Labels: :whale: iOS, PairProgramming

#134 작업 세부 페이지 기본 세팅
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO.xcodeproj/project.xcworkspace/xcuserdata/os.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Paging/TaskDetailBookmarkViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Paging/TaskDetailCommentViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Paging/TaskDetailPageViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Paging/TaskDetailSubTasksViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailInteractor.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailPresenter.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailWorker.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskList.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListInteractor.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListRouter.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskCollectionViewListCell.swift
  iOS/HalgoraeDO/Sources/Utils/UIViewController+segueIdentifier.swift
  iOS/HalgoraeDO/Sources/Views/Base.lproj/Main.storyboard
  iOS/HalgoraeDO/Sources/Views/ConfirmActionView/ConfirmActionView.swift
Labels: :whale: iOS

#132 client Header -& 검색 컴포넌트 작업 && Task & User 리팩토링
  client/src/api/myAxios.js
  client/src/api/task.js
  client/src/components/common/Header.vue
  client/src/components/task/Search.vue
  client/src/views/Home.vue
  client/vue.config.js
  server/package.json
  server/src/app.js
  server/src/controllers/comment.js
  server/src/controllers/task.js
  server/src/controllers/user.js
  server/src/models/seeders/index.js
  server/src/passport/naver-strategy.js
  server/src/routes/index.js
  server/src/routes/task.js
  server/src/services/comment.js
  server/src/services/task.js
  server/src/services/user.js
  server/test/project.api.test.js
  server/test/task.api.test.js
  server/test/test-seed.js
Labels: BE, Refactoring

#135 인증 로직 구현, private Router 구현
  client/.editorconfig
  client/src/App.vue
  client/src/api/myAxios.js
  client/src/api/user.js
  client/src/router/index.js
  client/src/store/auth.js
  client/src/views/Login.vue
  server/src/passport/jwt-strategy.js
Labels: FE

#137 메뉴 영역 구현 진행중
  client/.editorconfig
  client/src/App.vue
  client/src/api/label.js
  client/src/api/priority.js
  client/src/api/project.js
  client/src/components/common/Header.vue
  client/src/components/menu/FavoriteProjectList.vue
  client/src/components/menu/FilterList.vue
  client/src/components/menu/LabelList.vue
  client/src/components/menu/LeftMenu.vue
  client/src/components/menu/ProjectListContainer.vue
  client/src/plugins/vuetify.js
  client/src/router/index.js
  client/src/store/auth.js
  client/src/store/index.js
  client/src/store/label.js
  client/src/store/menu.js
  client/src/store/priority.js
  client/src/store/project.js
  client/src/store/task.js
  client/src/utils/date.js
  client/src/views/Home.vue
  client/src/views/Login.vue
  server/src/controllers/label.js
  server/src/routes/project.js
  server/src/routes/user.js
Labels: BE, FE

#140 BackEnd Label, Project Refactoring
  server/src/controllers/label.js
  server/src/controllers/project.js
  server/src/controllers/section.js
  server/src/controllers/task.js
  server/src/routes/index.js
  server/src/routes/label.js
  server/src/routes/project.js
  server/src/routes/task.js
  server/src/services/label.js
  server/src/services/project.js
  server/src/services/section.js
  server/src/services/task.js
  server/test/project.api.test.js
  server/test/task.api.test.js
Labels: BE, Refactoring

#141 작업 세부페이지 UI 작업
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskAddViewController.swift
  iOS/HalgoraeDO/Sources/Utils/Date+.swift
  iOS/HalgoraeDO/Sources/Views/Base.lproj/Main.storyboard
  iOS/HalgoraeDO/Sources/Views/BorderRadiusButton.swift
  iOS/HalgoraeDO/Sources/Views/DatePickerButtonView/DatePickerButtonView.swift
  iOS/HalgoraeDO/Sources/Views/DatePickerButtonView/DatePickerButtonView.xib
Labels: :whale: iOS

#145 #116 메뉴 화면 UI 구현
  iOS/HalgoraeDO/Sources/Scenes/Menu/MenuViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskAddViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskBoardSupplementaryView.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskSectionViewCell.swift
  iOS/HalgoraeDO/Sources/Utils/UIColor+.swift
  iOS/HalgoraeDO/Sources/Views/Base.lproj/Main.storyboard
Labels: :whale: iOS

#143 관리함 프로젝트 구현, 메뉴 영역 라우팅 구현
  client/src/api/project.js
  client/src/components/common/Header.vue
  client/src/components/menu/FavoriteProjectList.vue
  client/src/components/menu/FilterList.vue
  client/src/components/menu/LabelList.vue
  client/src/components/menu/LeftMenu.vue
  client/src/components/menu/ProjectListContainer.vue
  client/src/components/menu/index.vue
  client/src/components/project/ProjectContainer.vue
  client/src/components/today/TodayTasksContainer.vue
  client/src/store/auth.js
  client/src/store/project.js
  client/src/store/task.js
  client/src/utils/date.js
  client/src/views/Project.vue
  client/src/views/Today.vue
  server/src/controllers/label.js
  server/src/controllers/project.js
  server/src/controllers/task.js
  server/src/passport/naver-strategy.js
  server/src/routes/project.js
  server/src/services/project.js
  server/src/services/task.js
Labels: BE, FE

#146 작업 상세 화면 초기 구현, 라우팅 구현
  client/src/api/task.js
  client/src/components/project/ProjectContainer.vue
  client/src/components/project/TaskItem.vue
  client/src/components/task/TaskDetail.vue
  client/src/components/task/index.js
  client/src/router/index.js
  client/src/store/task.js
Labels: API, FE

#147 드래그앤 드랍 구현중
  client/src/api/project.js
  client/src/components/project/ProjectContainer.vue
  client/src/components/project/TaskItem.vue
  client/src/store/project.js
  client/src/store/task.js
  client/src/utils/array-index-swap.js
  server/src/routes/project.js
  server/src/services/section.js
Labels: FE

#149 작업 상세 화면 작업 & router 수정
  client/src/components/project/ProjectContainer.vue
  client/src/components/project/TaskItem.vue
  client/src/components/task/TaskDetail.vue
  client/src/components/today/TodayTasksContainer.vue
  client/src/router/index.js
  client/src/views/Project.vue
  client/src/views/Task.vue
Labels: FE, Refactoring

#150 피드백 반영 && alert 컴포넌트 구현
  client/src/App.vue
  client/src/api/label.js
  client/src/api/myAxios.js
  client/src/api/project.js
  client/src/api/task.js
  client/src/api/user.js
  client/src/components/common/Alert.vue
  client/src/components/menu/LeftMenu.vue
  client/src/components/project/ProjectContainer.vue
  client/src/router/index.js
  client/src/store/alert.js
  client/src/store/auth.js
  client/src/store/index.js
  client/src/store/label.js
  client/src/store/priority.js
  client/src/store/project.js
  client/src/store/task.js
  client/src/views/Login.vue
  client/src/views/Project.vue
Labels: FE

#151 디자인 수정 및 데모용 임시 처리
  iOS/HalgoraeDO/Sources/Scenes/Menu/MenuViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskBoardViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListRouter.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskSectionViewCell.swift
  iOS/HalgoraeDO/Sources/Utils/UIColor+.swift
  iOS/HalgoraeDO/Sources/Views/Base.lproj/Main.storyboard
  iOS/HalgoraeDO/Sources/Views/DatePickerButtonView/DatePickerButtonView.xib
Labels: :whale: iOS

#153 #101 Drag & Drop 구현
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListWorker.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskSectionViewCell.swift
Labels: :whale: iOS

#164 프로젝트 컴포넌트 캐싱, 불필요한 API 호출 방지
  client/src/App.vue
  client/src/components/menu/LeftMenu.vue
  client/src/store/auth.js
  client/src/store/project.js
  client/src/views/Home.vue
  client/src/views/Project.vue
Labels: FE

#165 작업 상세 화면 수정 & task API 관련 store 수정 및 API 수정
  client/package-lock.json
  client/src/components/task/Search.vue
  client/src/components/task/TaskDetail.vue
  client/src/store/task.js
  server/src/controllers/task.js
  server/src/routes/label.js
Labels: BE, FE

#156 네트워크 세팅
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO.xcodeproj/project.xcworkspace/xcuserdata/os.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/HalgoraeDO.xcodeproj/xcshareddata/xcschemes/HalgoraeDO.xcscheme
  iOS/HalgoraeDO/Sources/Service/DataRequest.swift
  iOS/HalgoraeDO/Sources/Service/Encoding/ParameterEncoding.swift
  iOS/HalgoraeDO/Sources/Service/Encoding/URLParameterEncoder.swift
  iOS/HalgoraeDO/Sources/Service/EndPointType.swift
  iOS/HalgoraeDO/Sources/Service/NetworkManager.swift
  iOS/HalgoraeDO/Sources/Service/SessionManager.swift
  iOS/ServiceTests/Info.plist
  iOS/ServiceTests/Mocks/CodableMock.swift
  iOS/ServiceTests/Mocks/DataRequestMock.swift
  iOS/ServiceTests/Mocks/EndPointMock.swift
  iOS/ServiceTests/Mocks/SessionManagerMock.swift
  iOS/ServiceTests/NetworkManagerTests.swift
  iOS/ServiceTests/RequestTests.swift
  iOS/ServiceTests/SessionManagerTests.swift
Labels: :whale: iOS

#169 작업 상세 화면 구현
  client/src/api/comment.js
  client/src/api/task.js
  client/src/components/comment/CommentFormContainer.vue
  client/src/components/comment/CommentItem.vue
  client/src/components/comment/CommentList.vue
  client/src/components/project/AddTask.vue
  client/src/components/project/TaskItem.vue
  client/src/components/task/ChildTaskList.vue
  client/src/components/task/TaskDetail.vue
  client/src/components/task/TaskDetailContainer.vue
  client/src/components/task/TaskDetailTabs.vue
  client/src/store/comment.js
  client/src/store/index.js
  client/src/store/task.js
  client/src/views/Task.vue
Labels: FE

#170 프로젝트 추가 화면 구현 && 즐겨찾기 구현
  client/src/api/project.js
  client/src/components/common/Alert.vue
  client/src/components/menu/FavoriteProjectList.vue
  client/src/components/menu/FilterList.vue
  client/src/components/menu/LabelList.vue
  client/src/components/menu/LeftMenu.vue
  client/src/components/menu/ProjectListContainer.vue
  client/src/components/project/AddProjectModal.vue
  client/src/components/project/AddTask.vue
  client/src/components/project/DeleteProjectModal.vue
  client/src/components/project/UpdateProjectModal.vue
  client/src/store/alert.js
  client/src/store/auth.js
  client/src/store/project.js
  client/src/store/task.js
  client/src/utils/color.js
  client/src/utils/today-string.js
  client/src/views/Home.vue
  client/src/views/Today.vue
  server/src/controllers/project.js
  server/src/models/project.js
  server/src/models/seeders/index.js
  server/src/services/project.js
  server/test/project.api.test.js
  server/test/test-seed.js
Labels: BE, FE

#171 섹션 추가기능 구현 / 작업 추가 form에 프로젝트 지정 기능 추가
  client/src/api/project.js
  client/src/components/common/Header.vue
  client/src/components/common/UpdatableTitle.vue
  client/src/components/project/AddSection.vue
  client/src/components/project/AddTask.vue
  client/src/components/project/ProjectContainer.vue
  client/src/components/project/ProjectContainerHeader.vue
  client/src/components/project/SectionContainer.vue
  client/src/components/project/TaskItem.vue
  client/src/store/project.js
  client/src/views/Home.vue
  server/src/services/section.js
Labels: FE

#173 Dto validation 셋업
  client/package.json
  server/.babelrc.js
  server/package.json
  server/src/controllers/task.js
  server/src/models/dto/task.js
  server/src/utils/validator.js
Labels: BE

#168 작업 목록 뷰 UI 수정 및 작업 추가 수정
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO/Sources/Models/Priority+PopoverViewModelType.swift
  iOS/HalgoraeDO/Sources/Models/Priority.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskAddViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskBoardViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskCollectionViewListCell.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskContentConfigure.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskContentView.swift
  iOS/HalgoraeDO/Sources/Service/Encoding/URLParameterEncoder.swift
  iOS/HalgoraeDO/Sources/Service/NetworkManager.swift
  iOS/HalgoraeDO/Sources/Service/SessionManager.swift
  iOS/HalgoraeDO/Sources/Utils/UIViewController+segueIdentifier.swift
  iOS/HalgoraeDO/Sources/Views/Base.lproj/Main.storyboard
  iOS/HalgoraeDO/Sources/Views/BorderRadiusButton.swift
  iOS/HalgoraeDO/Sources/Views/Popover/PopoverViewController.swift
  iOS/HalgoraeDO/Sources/Views/Popover/PopoverViewModelType.swift
  iOS/ServiceTests/Mocks/EndPointMock.swift
Labels: :whale: iOS

#175 Task DTO 수정 & create validation 로직 추가
  server/package.json
  server/src/controllers/task.js
  server/src/models/dto/error-messages.js
  server/src/models/dto/task.js
  server/src/utils/validator.js
Labels: BE, PairProgramming

#174 #116 프로젝트 추가 기능 구현
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO/Sources/Scenes/Menu/AddProjectViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/Menu/MenuViewController.swift
  iOS/HalgoraeDO/Sources/Views/Base.lproj/Main.storyboard
Labels: :whale: iOS

#180 task dto 적용 & task controller validation 추가
  server/.eslintrc.js
  server/jsconfig.json
  server/package-lock.json
  server/package.json
  server/src/controllers/task.js
  server/src/models/dto/error-messages.js
  server/src/models/dto/task.js
  server/src/routes/task.js
  server/src/utils/error-messages.js
  server/test/project.api.test.js
  server/test/project.task.api.test.js
  server/test/task.api.test.js
Labels: BE

#182 Project DTO 구현 && 로딩컴포넌트 구현
  client/package-lock.json
  client/src/App.vue
  client/src/components/common/Spinner.vue
  client/src/components/menu/FavoriteProjectList.vue
  client/src/components/menu/ProjectListContainer.vue
  client/src/components/project/AddProjectModal.vue
  client/src/components/today/TodayTasksContainer.vue
  client/src/mixins/ListMixins.js
  client/src/router/index.js
  client/src/utils/bus.js
  client/src/views/Home.vue
  client/src/views/Login.vue
  client/src/views/Project.vue
  client/src/views/Today.vue
  server/src/controllers/project.js
  server/src/models/dto/project.js
  server/src/models/project.js
  server/src/services/project.js
Labels: BE, FE

#176 메뉴 API 연동 및 즐겨찾기 개선
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO.xcodeproj/xcshareddata/xcschemes/HalgoraeDO.xcscheme
  iOS/HalgoraeDO/Sources/Models/Bookmark.swift
  iOS/HalgoraeDO/Sources/Models/Comment.swift
  iOS/HalgoraeDO/Sources/Models/Priority.swift
  iOS/HalgoraeDO/Sources/Models/Project.swift
  iOS/HalgoraeDO/Sources/Models/Section.swift
  iOS/HalgoraeDO/Sources/Models/Task.swift
  iOS/HalgoraeDO/Sources/Scenes/Menu/MenuInteractor.swift
  iOS/HalgoraeDO/Sources/Scenes/Menu/MenuModels.swift
  iOS/HalgoraeDO/Sources/Scenes/Menu/MenuPresenter.swift
  iOS/HalgoraeDO/Sources/Scenes/Menu/MenuRouter.swift
  iOS/HalgoraeDO/Sources/Scenes/Menu/MenuViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/Menu/MenuWorker.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskList.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListViewController.swift
  iOS/HalgoraeDO/Sources/Service/DataRequest.swift
  iOS/HalgoraeDO/Sources/Service/EndPoints/ProjectEndPoint.swift
  iOS/HalgoraeDO/Sources/Service/NetworkManager.swift
  iOS/HalgoraeDO/Sources/Service/SessionManager.swift
Labels: :whale: iOS

#187 release에서 수정한 사항 반영
  .DS_Store
  .github/ISSUE_TEMPLATE/api---.md
  .github/ISSUE_TEMPLATE/api.md
  .github/ISSUE_TEMPLATE/component.md
  .github/ISSUE_TEMPLATE/discussion.md
  client/package.json
  server/.babelrc.js
  server/jsconfig.json
  server/package-lock.json
  server/package.json
  server/src/models/dto/section.js
Labels: BE, DEPLOY

#188 댓글 dto & contoller validation
  server/src/controllers/comment.js
  server/src/models/comment.js
  server/src/models/dto/comment.js
  server/src/utils/error-messages.js
  server/test/task.api.test.js
  server/test/task.comment.api.test.js
Labels: BE

#190 하위작업 탭 패치 구현
  iOS/HalgoraeDO/Sources/Models/Task.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Paging/TaskDetailSubTasksViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailInteractor.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailModels.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailPresenter.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailWorker.swift
  iOS/HalgoraeDO/Sources/Service/EndPoints/TaskEndPoint.swift
Labels: :whale: iOS

#193 list뷰 section구현 및 drag & drop 수정
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO/Sources/Models/Section.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailInteractor.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskBoardSupplementaryView.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskSectionViewCell.swift
  iOS/HalgoraeDO/Sources/Views/Base.lproj/Main.storyboard
Labels: :whale: iOS

#195 백앤드 리팩토링 & validation 로직 수정 & task 비즈니스 로직 에러 핸들링
  server/src/controllers/label.js
  server/src/controllers/project.js
  server/src/controllers/task.js
  server/src/models/alarm.js
  server/src/models/associations.js
  server/src/models/dto/task.js
  server/src/models/label.js
  server/src/models/priority.js
  server/src/models/seeders/index.js
  server/src/models/task.js
  server/src/routes/index.js
  server/src/routes/label.js
  server/src/routes/project.js
  server/src/services/authorization-check.js
  server/src/services/label.js
  server/src/services/project.js
  server/src/services/task.js
  server/src/utils/error-codes.js
  server/src/utils/error-messages.js
  server/test/label.api.test.js
  server/test/project.api.test.js
  server/test/project.task.api.test.js
  server/test/task.api.test.js
  server/test/test-seed.js
Labels: BE

#196 whale bookmark API 테스트 && 각종 에러 해결
  client/src/api/myAxios.js
  client/src/api/task.js
  client/src/components/common/Spinner.vue
  client/src/components/menu/FavoriteProjectList.vue
  client/src/components/menu/LeftMenu.vue
  client/src/components/menu/ProjectListContainer.vue
  client/src/components/project/AddTask.vue
  client/src/components/project/SectionContainer.vue
  client/src/components/project/TaskItem.vue
  client/src/components/today/TaskGroupPerDate.vue
  client/src/components/today/TodayTasksContainer.vue
  client/src/mixins/ListMixins.js
  client/src/router/index.js
  client/src/store/alert.js
  client/src/store/auth.js
  client/src/store/comment.js
  client/src/store/dragAndDrop.js
  client/src/store/index.js
  client/src/store/label.js
  client/src/store/priority.js
  client/src/store/project.js
  client/src/store/task.js
  client/src/utils/whaleApi/index.js
  client/src/views/Project.vue
  server/src/controllers/project.js
  server/src/controllers/user.js
  whale/background.js
  whale/manifest.json
Labels: FE

#197 웨일 API 이용한 알람 구현
  client/src/components/project/AddTask.vue
  client/src/store/project.js
  client/src/utils/markdown.js
  client/src/utils/whaleApi/index.js
  whale/background.js
  whale/manifest.json
Labels: FE

#199 프론트앤드 오류 수정
  client/src/api/project.js
  client/src/components/project/AddTask.vue
  client/src/components/project/SectionContainer.vue
  client/src/components/project/TaskItem.vue
  client/src/store/project.js
  client/src/store/task.js
  client/src/views/Task.vue
  server/src/services/task.js
  whale/manifest.json
Labels: FE, PairProgramming

#200 event bus를 활용한 taskDetail 라우팅 로직 변경
  client/src/components/project/AddTask.vue
  client/src/components/project/ProjectContainer.vue
  client/src/components/project/TaskItem.vue
  client/src/components/task/TaskDetailContainer.vue
  client/src/views/Task.vue
Labels: FE

#201 작업 추가 관련 수정
  client/src/components/project/AddTask.vue
  client/src/components/project/ProjectContainer.vue
  client/src/components/project/SectionContainer.vue
  client/src/components/project/TaskItem.vue
  client/src/components/task/TaskDetailContainer.vue
  server/src/services/project.js
  server/src/services/task.js
Labels: BE, FE

#202 whale runtime 에러처리
  client/src/mixins/SpinnerMixin.js
  client/src/utils/whaleApi/index.js
  client/src/views/Home.vue
  client/src/views/Login.vue
  client/src/views/Project.vue
  client/src/views/Task.vue
  client/src/views/Today.vue
Labels: FE

#203 Board view Drag & Drop 수정 / 추가 개발
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskBoardViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskSectionViewCell.swift
  iOS/HalgoraeDO/Sources/Views/Base.lproj/Main.storyboard
Labels: :whale: iOS

#194 코멘트 생성 구현
  iOS/HalgoraeDO/Sources/Models/Task.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Paging/TaskDetailCommentViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Paging/Views/TaskCommentCell.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Paging/Views/TaskCommentImageCell.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Paging/Views/TaskDetailContentsCellCollectionViewCell.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailInteractor.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailModels.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailPresenter.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailWorker.swift
Labels: :whale: iOS

#205 전체 프로젝트 조회 API
  server/src/controllers/project.js
  server/src/services/project.js
  server/src/services/task.js
Labels: BE

#207 API 수정
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO/Sources/Models/Response/ResponseMessage.swift
  iOS/HalgoraeDO/Sources/Models/Response/ResponseProject.swift
  iOS/HalgoraeDO/Sources/Scenes/Menu/MenuWorker.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Paging/TaskDetailBookmarkViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Paging/TaskDetailSubTasksViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Paging/Views/TaskDetailCommentCell.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskAddViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskList.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListInteractor.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListRouter.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListWorker.swift
  iOS/HalgoraeDO/Sources/Service/EndPoints/TaskEndPoint.swift
  iOS/HalgoraeDO/Sources/Views/Base.lproj/Main.storyboard
Labels: :whale: iOS

#208 API 연동 개발
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO/Sources/Entry/AppDelegate.swift
  iOS/HalgoraeDO/Sources/Entry/SceneDelegate.swift
  iOS/HalgoraeDO/Sources/Models/Project.swift
  iOS/HalgoraeDO/Sources/Models/Section.swift
  iOS/HalgoraeDO/Sources/Models/Task.swift
  iOS/HalgoraeDO/Sources/Scenes/Menu/MenuInteractor.swift
  iOS/HalgoraeDO/Sources/Scenes/Menu/MenuModels.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskAddViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskBoardViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListInteractor.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListModels.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListWorker.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskSectionViewCell.swift
  iOS/HalgoraeDO/Sources/Service/EndPoints/ProjectEndPoint.swift
  iOS/HalgoraeDO/Sources/Service/EndPoints/TaskEndPoint.swift
  iOS/HalgoraeDO/Sources/Views/Base.lproj/Main.storyboard
Labels: :whale: iOS

#209 다크모드 && 각종 UI 수정 && API 수정 && 북마크 UI 구현
  client/src/api/project.js
  client/src/components/bookmark/BookmarkFormContainer.vue
  client/src/components/bookmark/BookmarkItem.vue
  client/src/components/bookmark/BookmarkList.vue
  client/src/components/comment/CommentFormContainer.vue
  client/src/components/comment/CommentItem.vue
  client/src/components/comment/CommentList.vue
  client/src/components/common/Alert.vue
  client/src/components/common/Header.vue
  client/src/components/common/Spinner.vue
  client/src/components/common/UpdatableTitle.vue
  client/src/components/menu/BookmarkList.vue
  client/src/components/menu/FavoriteProjectList.vue
  client/src/components/menu/LeftMenu.vue
  client/src/components/menu/ProjectListContainer.vue
  client/src/components/project/AddProjectModal.vue
  client/src/components/project/AddTask.vue
  client/src/components/project/ProjectContainer.vue
  client/src/components/project/ProjectContainerHeader.vue
  client/src/components/project/SectionContainer.vue
  client/src/components/project/TaskItem.vue
  client/src/components/task/Search.vue
  client/src/components/task/TaskDetailContainer.vue
  client/src/components/task/TaskDetailTabs.vue
  client/src/components/today/TaskGroupPerDate.vue
  client/src/components/today/TodayTasksContainer.vue
  client/src/plugins/vuetify.js
  client/src/store/bookmark.js
  client/src/store/dragAndDrop.js
  client/src/store/index.js
  client/src/store/project.js
  client/src/store/task.js
  client/src/utils/markdown.js
  client/src/utils/whaleApi/index.js
  client/src/views/Home.vue
  client/src/views/Project.vue
  client/src/views/Task.vue
  client/src/views/Today.vue
  client/vue.config.js
  server/src/controllers/project.js
  server/src/routes/project.js
  server/src/services/project.js
  server/src/services/task.js
  server/test/project.api.test.js
  whale/background.js
Labels: BE, FE

#210 버그 수정 및 composition api 활용 하위 task 위치변경 구현
  client/package.json
  client/src/api/task.js
  client/src/components/common/Header.vue
  client/src/components/project/AddTask.vue
  client/src/components/project/ChildTaskList.vue
  client/src/components/project/SectionContainer.vue
  client/src/components/project/TaskItem.vue
  client/src/components/today/TaskGroupPerDate.vue
  client/src/composables/useDragDropContainer.js
  client/src/main.js
  client/src/store/dragAndDrop.js
  client/src/store/task.js
  server/src/controllers/task.js
  server/src/routes/task.js
  server/src/services/project.js
  server/src/services/task.js
  whale/background.js
Labels: BE, FE

#213 백엔드 서비스 에러 처리 & custom error
  server/src/controllers/comment.js
  server/src/controllers/task.js
  server/src/loaders/error-handler.js
  server/src/models/bookmark.js
  server/src/models/comment.js
  server/src/models/dto/comment.js
  server/src/models/dto/project.js
  server/src/models/dto/section.js
  server/src/models/dto/task.js
  server/src/models/project.js
  server/src/models/section.js
  server/src/models/seeders/index.js
  server/src/models/task.js
  server/src/models/user.js
  server/src/services/authority-check.js
  server/src/services/comment.js
  server/src/services/project.js
  server/src/services/task.js
  server/src/utils/auth.js
  server/src/utils/custom-error.js
  server/src/utils/error-codes.js
  server/src/utils/error-messages.js
  server/src/utils/handler.js
  server/src/utils/params-validator.js
  server/src/utils/validator.js
  server/test/project.api.test.js
  server/test/project.section.api.test.js
  server/test/task.api.test.js
  server/test/task.comment.api.test.js
  server/test/test-seed.js
Labels: BE

#214 API 연동 및 detail 뷰 구현
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO/Sources/Models/Comment.swift
  iOS/HalgoraeDO/Sources/Models/Response/ResponseDetail.swift
  iOS/HalgoraeDO/Sources/Models/Task.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Paging/TaskDetailBookmarkViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Paging/TaskDetailCommentViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Paging/Views/CommentAddView.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Paging/Views/CommentAddView.xib
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailInteractor.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailModels.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailPresenter.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailWorker.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskList.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListInteractor.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListModels.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListPresenter.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListWorker.swift
  iOS/HalgoraeDO/Sources/Service/EndPoints/BookmarkEndPoint.swift
  iOS/HalgoraeDO/Sources/Service/EndPoints/TaskEndPoint.swift
  iOS/HalgoraeDO/Sources/Views/Base.lproj/Main.storyboard
Labels: :whale: iOS

#215 코어데이터 적용
  iOS/EndPointMO+CoreDataClass.swift
  iOS/EndPointMO+CoreDataProperties.swift
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO.xcodeproj/xcshareddata/xcschemes/HalgoraeDO.xcscheme
  iOS/HalgoraeDO/Sources/Core Data/APIStorageType.swift
  iOS/HalgoraeDO/Sources/Core Data/EndPointStorage.swift
  iOS/HalgoraeDO/Sources/Core Data/HalgoraeDO.xcdatamodeld/HalgoraeDO.xcdatamodel/contents
  iOS/HalgoraeDO/Sources/Core Data/Models/Bookmark+CoreDataClass.swift
  iOS/HalgoraeDO/Sources/Core Data/Models/Bookmark+CoreDataProperties.swift
  iOS/HalgoraeDO/Sources/Core Data/Models/Comment+CoreDataClass.swift
  iOS/HalgoraeDO/Sources/Core Data/Models/Comment+CoreDataProperties.swift
  iOS/HalgoraeDO/Sources/Core Data/Models/Project+CoreDataClass.swift
  iOS/HalgoraeDO/Sources/Core Data/Models/Project+CoreDataProperties.swift
  iOS/HalgoraeDO/Sources/Core Data/Models/Section+CoreDataClass.swift
  iOS/HalgoraeDO/Sources/Core Data/Models/Section+CoreDataProperties.swift
  iOS/HalgoraeDO/Sources/Core Data/Models/Task+CoreDataClass.swift
  iOS/HalgoraeDO/Sources/Core Data/Models/Task+CoreDataProperties.swift
  iOS/HalgoraeDO/Sources/Core Data/PersistentContainer.swift
  iOS/HalgoraeDO/Sources/Core Data/ProjectStorage.swift
  iOS/HalgoraeDO/Sources/Core Data/Storage.swift
  iOS/HalgoraeDO/Sources/Core Data/TaskStorage.swift
  iOS/HalgoraeDO/Sources/Entry/AppDelegate.swift
  iOS/HalgoraeDO/Sources/Entry/SceneDelegate.swift
  iOS/HalgoraeDO/Sources/Models/Bookmark.swift
  iOS/HalgoraeDO/Sources/Models/Comment.swift
  iOS/HalgoraeDO/Sources/Models/Project.swift
  iOS/HalgoraeDO/Sources/Models/Section.swift
  iOS/HalgoraeDO/Sources/Models/Task.swift
  iOS/HalgoraeDO/Sources/Scenes/Menu/MenuInteractor.swift
  iOS/HalgoraeDO/Sources/Scenes/Menu/MenuModels.swift
  iOS/HalgoraeDO/Sources/Scenes/Menu/MenuViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/Menu/MenuWorker.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailInteractor.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskBoardViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskList.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListInteractor.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListModels.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListViewController.swift
  iOS/HalgoraeDO/Sources/Service/Encoding/ParameterEncoding.swift
  iOS/HalgoraeDO/Sources/Service/EndPoints/DefaultEndPoint.swift
  iOS/HalgoraeDO/Sources/Service/EndPoints/ProjectEndPoint.swift
  iOS/HalgoraeDO/Sources/Service/NetworkMonitor.swift
  iOS/HalgoraeDO/Sources/Utils/Date+.swift
  iOS/HalgoraeDO/Sources/Utils/Encodable+encodeData.swift
  iOS/HalgoraeDO/Sources/Views/Base.lproj/Main.storyboard
Labels: :whale: iOS

#216 comment 에러 처리
  server/src/controllers/comment.js
  server/src/models/dto/comment.js
  server/src/services/authority-check.js
  server/src/services/comment.js
  server/src/services/task.js
  server/test/task.comment.api.test.js
  server/test/test-seed.js
Labels: BE

#217 Today 화면 에러 처리
  client/package-lock.json
  client/src/components/bookmark/BookmarkItem.vue
  client/src/components/comment/CommentItem.vue
  client/src/components/comment/CommentList.vue
  client/src/components/project/AddProjectModal.vue
  client/src/components/project/SectionContainer.vue
  client/src/components/project/UpdateProjectModal.vue
  client/src/components/task/TaskDetailContainer.vue
  client/src/components/today/TaskGroupPerDate.vue
  client/src/components/today/TodayTasksContainer.vue
  client/src/store/comment.js
  client/src/store/task.js
  client/src/utils/date.js
  client/src/views/Task.vue
  client/src/views/Today.vue
  server/src/models/dto/task.js
  server/src/utils/custom-error.js
  server/test/project.task.api.test.js
Labels: FE

#218 버그 수정
  client/src/components/common/Header.vue
  client/src/components/project/AddTask.vue
  client/src/components/project/SectionContainer.vue
  client/src/components/project/TaskItem.vue
  client/src/composables/useDragDropItem.js
  whale/manifest.json
Labels: FE

#221 북마크 API 작업
  server/src/controllers/bookmark.js
  server/src/models/dto/bookmark.js
  server/src/routes/task.js
  server/src/services/authority-check.js
  server/src/services/bookmark.js
  server/src/utils/params-validator.js
  server/test/bookmark.api.test.js
  server/test/test-seed.js
Labels: API, BE

#222 comment UI 구현 && 북마크 UI 구현
  client/src/api/bookmark.js
  client/src/api/comment.js
  client/src/components/bookmark/BookmarkFormContainer.vue
  client/src/components/bookmark/BookmarkItem.vue
  client/src/components/bookmark/BookmarkList.vue
  client/src/components/comment/CommentFormContainer.vue
  client/src/components/comment/CommentItem.vue
  client/src/components/comment/CommentList.vue
  client/src/components/menu/BookmarkList.vue
  client/src/components/task/TaskDetailContainer.vue
  client/src/components/task/TaskDetailTabs.vue
  client/src/store/bookmark.js
  client/src/store/comment.js
  client/src/utils/markdown.js
  client/src/views/Task.vue
Labels: FE

#226 테스트코드 리팩토링
  server/test/project.api.test.js
  server/test/project.task.api.test.js
  server/test/user.api.test.js
Labels: BE

#225 서비스 테스트 수정 보완
  iOS/HalgoraeDO/Sources/Service/DataRequest.swift
  iOS/HalgoraeDO/Sources/Service/NetworkManager.swift
  iOS/HalgoraeDO/Sources/Service/SessionManager.swift
  iOS/ServiceTests/Mocks/DataRequestMock.swift
  iOS/ServiceTests/Mocks/SessionManagerMock.swift
  iOS/ServiceTests/RequestTests.swift
Labels: :whale: iOS

#229 iOS 네아로 redirection url 구현
  server/src/controllers/user.js
Labels: BE

#230 네아로 추가
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO.xcodeproj/xcshareddata/xcschemes/HalgoraeDO.xcscheme
  iOS/HalgoraeDO/Resources/Assets.xcassets/whale.imageset/22.png
  iOS/HalgoraeDO/Resources/Assets.xcassets/whale.imageset/Contents.json
  iOS/HalgoraeDO/Resources/Colors.xcassets/halgoraedoBackground.colorset/Contents.json
  iOS/HalgoraeDO/Resources/Colors.xcassets/halgoraedoDarkBlue.colorset/Contents.json
  iOS/HalgoraeDO/Resources/Colors.xcassets/halgoraedoMint.colorset/Contents.json
  iOS/HalgoraeDO/Sources/Scenes/SignIn/SignInViewController.swift
  iOS/HalgoraeDO/Sources/Service/EndPointType.swift
  iOS/HalgoraeDO/Sources/Service/EndPoints/BookmarkEndPoint.swift
  iOS/HalgoraeDO/Sources/Service/EndPoints/CommentEndPoint.swift
  iOS/HalgoraeDO/Sources/Service/EndPoints/ProjectEndPoint.swift
  iOS/HalgoraeDO/Sources/Service/EndPoints/TaskEndPoint.swift
  iOS/HalgoraeDO/Sources/Storage/AuthManager.swift
  iOS/HalgoraeDO/Sources/Utils/UIColor+.swift
  iOS/HalgoraeDO/Sources/Views/Base.lproj/Main.storyboard
  iOS/HalgoraeDO/Supporting Files/Info.plist
Labels: :whale: iOS

#231 Board뷰 Drag Drop개발
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO/Sources/Scenes/Menu/MenuViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/SignIn/SignInViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Paging/TaskDetailSubTasksViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailModels.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailPresenter.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskBoardViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskList.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListInteractor.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListModels.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListPresenter.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListRouter.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListWorker.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskCollectionViewListCell.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskSectionViewCell.swift
  iOS/HalgoraeDO/Sources/Service/EndPoints/TaskEndPoint.swift
  iOS/HalgoraeDO/Sources/Views/Base.lproj/Main.storyboard
Labels: :whale: iOS

#232 drag drop interactor 구현
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskBoardViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskDragDropInteractor.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListDisplayLogic.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListInteractor.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListModels.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListPresenter.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListViewController.swift
  iOS/HalgoraeDO/Sources/Views/Base.lproj/Main.storyboard
Labels: :whale: iOS

#236 BackEnd 에러 처리 & test 케이스 추가 & 1차 리팩토링
  client/src/views/Task.vue
  server/src/controllers/project.js
  server/src/controllers/section.js
  server/src/controllers/task.js
  server/src/models/dto/bookmark.js
  server/src/models/dto/comment.js
  server/src/models/dto/position.js
  server/src/models/dto/project.js
  server/src/models/dto/section.js
  server/src/models/dto/task.js
  server/src/services/project.js
  server/src/services/section.js
  server/src/utils/custom-error.js
  server/src/utils/handler.js
  server/src/utils/params-validator.js
  server/src/utils/today-start-end.js
  server/src/utils/validator.js
  server/test/bookmark.api.test.js
  server/test/position.api.test.js
  server/test/project.api.test.js
  server/test/project.section.api.test.js
  server/test/project.task.api.test.js
  server/test/task.api.test.js
  server/test/task.comment.api.test.js
Labels: BE, Refactoring

#233 Feat/ios/refactor service tests
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO.xcodeproj/project.xcworkspace/xcuserdata/os.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/HalgoraeDO.xcodeproj/xcshareddata/xcschemes/HalgoraeDO.xcscheme
  iOS/HalgoraeDO.xcodeproj/xcshareddata/xcschemes/ServiceTests.xcscheme
  iOS/HalgoraeDO.xcodeproj/xcuserdata/os.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS/HalgoraeDO/Sources/Scenes/Menu/MenuModels.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Paging/Views/CommentAddView.xib
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Paging/Views/TaskDetailContentsCellCollectionViewCell.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskBoardViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListInteractor.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListModels.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListWorker.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskBoardSupplementaryView.swift
  iOS/HalgoraeDO/Sources/Service/DataRequest.swift
  iOS/HalgoraeDO/Sources/Service/DataResponsing.swift
  iOS/HalgoraeDO/Sources/Views/DatePickerButtonView/DatePickerButtonView.xib
  iOS/ServiceTests/Mocks/DataRequestMock.swift
  iOS/ServiceTests/NetworkManagerTests.swift
  iOS/ServiceTests/RequestTests.swift
  iOS/ServiceTests/SessionManagerTests.swift
  iOS/TaskListTests/Info.plist
  iOS/TaskListTests/Mock/TaskListInteractorMock.swift
  iOS/TaskListTests/Mock/TaskListPresenterMock.swift
  iOS/TaskListTests/Mock/TaskListViewControllerMock.swift
  iOS/TaskListTests/Mock/TaskListWorkerMock.swift
  iOS/TaskListTests/PersistentMock.swift
  iOS/TaskListTests/TaskListInteractorTests.swift
  iOS/TaskListTests/TaskListWorkerTests.swift
  iOS/TaskListTests/WorkerTests.swift
Labels: :whale: iOS, Refactoring

#239 Board Drag Drop interactor 구조 변경
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  iOS/HalgoraeDO/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  iOS/HalgoraeDO/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  iOS/HalgoraeDO/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  iOS/HalgoraeDO/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  iOS/HalgoraeDO/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  iOS/HalgoraeDO/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  iOS/HalgoraeDO/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  iOS/HalgoraeDO/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  iOS/HalgoraeDO/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  iOS/HalgoraeDO/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  iOS/HalgoraeDO/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Paging/Views/CommentAddView.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailContentsCellCollectionViewCell.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/TaskDetailViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskBoardViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskDragDropInteractor.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListDisplayLogic.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListInteractor.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListModels.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListPresenter.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskContentView.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskSectionViewCell.swift
  iOS/HalgoraeDO/Sources/Utils/UIView+shadow.swift
Labels: :whale: iOS

#237 각종 에러 해결 && UI수정 && NOTFOUND 컴포넌트 구현
  client/package-lock.json
  client/src/App.vue
  client/src/api/myAxios.js
  client/src/components/common/Alert.vue
  client/src/components/common/UpdatableTitle.vue
  client/src/components/home/MainHeader.vue
  client/src/components/home/MainHeaderSearchTask.vue
  client/src/components/home/menu/BookmarkList.vue
  client/src/components/home/menu/FavoriteProjectList.vue
  client/src/components/home/menu/LeftMenu.vue
  client/src/components/home/menu/ProjectListContainer.vue
  client/src/components/project/section/SectionContainer.vue
  client/src/components/task/AddTask.vue
  client/src/components/task/TaskDetailContainer.vue
  client/src/components/task/TaskDetailTabs.vue
  client/src/components/task/TaskItem.vue
  client/src/components/today/TaskGroupPerDate.vue
  client/src/components/today/TodayTasksContainer.vue
  client/src/router/index.js
  client/src/store/task.js
  client/src/views/NotFound.vue
  client/src/views/Project.vue
  client/src/views/Task.vue
  server/src/passport/naver-strategy.js
Labels: FE

#241 project findOrCreate 다시 추가
  server/src/services/project.js
Labels: BE

#238 FE 리팩토링: 컴포넌트 분리 및 완료작업 필터 문제 해결
  client/package-lock.json
  client/src/components/home/menu/FilterList.vue
  client/src/components/home/menu/LabelList.vue
  client/src/components/home/menu/LeftMenu.vue
  client/src/components/home/menu/LeftMenuBookmarkList.vue
  client/src/components/home/menu/LeftMenuFavoriteProjectList.vue
  client/src/components/home/menu/LeftMenuProjectList.vue
  client/src/components/home/menu/LeftMenuProjectListContainer.vue
  client/src/components/project/ProjectContainer.vue
  client/src/components/project/ProjectContainerHeader.vue
  client/src/components/project/ProjectDeleteModal.vue
  client/src/components/project/ProjectFormModal.vue
  client/src/components/project/ProjectFormModalButtonContainer.vue
  client/src/components/project/ProjectFormModalColor.vue
  client/src/components/project/ProjectFormModalTitle.vue
  client/src/components/project/UpdateProjectModal.vue
  client/src/components/project/section/SectionContainer.vue
  client/src/components/task/AddTask.vue
  client/src/components/task/AddTaskAlarmPicker.vue
  client/src/components/task/AddTaskButtonContainerAfter.vue
  client/src/components/task/AddTaskButtonContainerBefore.vue
  client/src/components/task/AddTaskDueDatePicker.vue
  client/src/components/task/AddTaskProjectPicker.vue
  client/src/components/task/ChildTaskList.vue
  client/src/components/task/TaskDetailContainer.vue
  client/src/components/task/TaskItem.vue
  client/src/composables/useDragDropItem.js
  client/src/composables/useDroppable.js
  client/src/store/project.js
  server/src/services/section.js
Labels: Refactoring

#243 코드 수정 및 디자인 수정, launch 스크린 적용
  iOS/HalgoraeDO/Resources/Assets.xcassets/launch.imageset/Contents.json
  iOS/HalgoraeDO/Resources/Assets.xcassets/launch.imageset/launch.png
  iOS/HalgoraeDO/Sources/Entry/AppDelegate.swift
  iOS/HalgoraeDO/Sources/Entry/Base.lproj/LaunchScreen.storyboard
  iOS/HalgoraeDO/Sources/Models/Priority+PopoverViewModelType.swift
  iOS/HalgoraeDO/Sources/Scenes/Menu/MenuModels.swift
  iOS/HalgoraeDO/Sources/Scenes/Menu/MenuViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/SignIn/SignInViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Paging/TaskDetailCommentViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskAddViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskBoardViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListInteractor.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListPresenter.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListRouter.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskSectionViewCell.swift
  iOS/HalgoraeDO/Sources/Utils/UIView+shadow.swift
  iOS/HalgoraeDO/Sources/Views/Base.lproj/Main.storyboard
Labels: :whale: iOS

#246 불필요한 파일 제거
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO/Sources/Storage/TaskStorage.swift
Labels: :whale: iOS

#247 누락된 레퍼런스 파일 추가
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO.xcodeproj/project.xcworkspace/xcuserdata/os.xcuserdatad/UserInterfaceState.xcuserstate
Labels: :whale: iOS

#249 Google auth 구현
  client/src/assets/googlelogin.png
  client/src/views/Login.vue
  server/.sample.env
  server/package.json
  server/src/controllers/user.js
  server/src/models/user.js
  server/src/passport/google-strategy.js
  server/src/passport/index.js
  server/src/passport/naver-strategy.js
  server/src/routes/user.js
  server/src/utils/auth.js
Labels: BE

#251 test coverage 명령어 추가 & package.json 배포 버전 수정
  client/package.json
  server/.gitignore
  server/package-lock.json
  server/package.json
Labels: API, BE, documentation

#250 리펙토링
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO/Resources/Assets.xcassets/Contents.json
  iOS/HalgoraeDO/Resources/Assets.xcassets/check .imageset/Contents.json
  iOS/HalgoraeDO/Resources/Assets.xcassets/check .imageset/check .png
  iOS/HalgoraeDO/Resources/Assets.xcassets/check_empty.imageset/Contents.json
  iOS/HalgoraeDO/Resources/Assets.xcassets/check_empty.imageset/check_empty.png
  iOS/HalgoraeDO/Resources/Assets.xcassets/whale.imageset/22.png
  iOS/HalgoraeDO/Sources/Scenes/Menu/MenuViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/Menu/Views/MenuGenerator.swift
  iOS/HalgoraeDO/Sources/Scenes/SignIn/SignInViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Paging/TaskDetailSubTasksViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Views/TaskDetailCommentCell.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Views/TaskDetailContentsCellCollectionViewCell.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskBoardViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListRouter.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/AddSectionViewCell.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/LineView.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskBoardSupplementaryView.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskCollectionViewListCell.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskListGenerator.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskSectionViewCell.swift
  iOS/HalgoraeDO/Sources/Service/EndPointType.swift
  iOS/HalgoraeDO/Sources/Service/NetworkMonitor.swift
  iOS/HalgoraeDO/Sources/Utils/UIView+slideRight.swift
  iOS/HalgoraeDO/Sources/Views/Base.lproj/Main.storyboard
  iOS/HalgoraeDO/Sources/Views/SimpleAlertController.swift
Labels: :whale: iOS

#253 코드 리펙토링
  iOS/HalgoraeDO.xcodeproj/project.pbxproj
  iOS/HalgoraeDO/Resources/Assets.xcassets/Contents.json
  iOS/HalgoraeDO/Resources/Assets.xcassets/check .imageset/Contents.json
  iOS/HalgoraeDO/Resources/Assets.xcassets/check .imageset/check .png
  iOS/HalgoraeDO/Resources/Assets.xcassets/check_empty.imageset/Contents.json
  iOS/HalgoraeDO/Resources/Assets.xcassets/check_empty.imageset/check_empty.png
  iOS/HalgoraeDO/Resources/Assets.xcassets/whale.imageset/22.png
  iOS/HalgoraeDO/Sources/Scenes/Menu/MenuViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/Menu/Views/MenuGenerator.swift
  iOS/HalgoraeDO/Sources/Scenes/SignIn/SignInViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Paging/TaskDetailSubTasksViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Views/TaskDetailCommentCell.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskDetail/Views/TaskDetailContentsCellCollectionViewCell.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskBoardViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListRouter.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/TaskListViewController.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/AddSectionViewCell.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/LineView.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskBoardSupplementaryView.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskCollectionViewListCell.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskListGenerator.swift
  iOS/HalgoraeDO/Sources/Scenes/TaskList/Views/TaskSectionViewCell.swift
  iOS/HalgoraeDO/Sources/Service/EndPointType.swift
  iOS/HalgoraeDO/Sources/Service/NetworkMonitor.swift
  iOS/HalgoraeDO/Sources/Utils/UIView+slideRight.swift
  iOS/HalgoraeDO/Sources/Views/Base.lproj/Main.storyboard
  iOS/HalgoraeDO/Sources/Views/SimpleAlertController.swift
Labels: :whale: iOS, Refactoring

#260 FIX: task 완료여부 변경기능 버그수정
  client/src/components/task/TaskItem.vue
  client/src/store/task.js
Labels: FE

#261 [FIX] dueDate를 내년으로 설정했을때 오류 해결
  server/src/utils/date.js
  server/test/project.task.api.test.js
Labels: BE, bug
